server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: promtail-container-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: 'loki-user-api-application-job'
    static_configs:
      - targets:
          - localhost
        labels:
          job: loki-user-api-application-promtail
          __path__: /user-api-application/logs/app.log