scrape_configs:
  - job_name: 'prometheus-user-api-application-job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'user-api-application-label'
