spring:
  application:
    name: userapi-server
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: postgres
    password: password
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off

management:
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  # All traces should be sent to latency analysis tool
  tracing:
    sampling:
      probability: 1

  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %level %logger{36} - %msg%n"
  level:
    root: info
    com.example: debug
  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 7
    clean-history-on-start: true

loki:
  url: "http://localhost:3100"